- id: text-command
  language: system
  name: Custom command for text files, passed to `bash -c`
  types: [text]
  entry: bash -c
- id: text-command-always
  language: system
  name: Custom command for text files, passed to `bash -c`
  types: [text]
  entry: bash -c
  always_run: true


